version: '3.8'

services:
  db:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./src/database/postgres_data:/var/lib/postgresql/data
  
  test-db:
    image: postgres:16
    container_name: test-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: test
    ports:
      - "5433:5432"
    volumes:
      - ./src/database/test_postgres_data:/var/lib/postgresql/data
  
volumes:
  postgres_data:
    driver: local
  test_postgres_data:
    driver: local